const httpStatusCodes = {
    OK : 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    ALREADY_REPORTED: 208,
    MULTIPLE_RESPONSE: 300,
    MOVED_PERMANENTLY: 301,
    CHECK_OTHER: 303,
    NOT_MODIFIED: 304, //FOR CACHING PURPOSE, TELLS CLIENT THAT THE RESOURSE IS NOT CHANGED YOU CAN USED THE CACHED VERSION
    USE_PROXY: 306,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403, //CLIENT DOESN'T HAVE ACCESS RIGHTS TO ACCESS THE RESOURCES
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    REQUEST_TIMEOUT: 408,
    PERMANENTLY_DELETED: 410,
    PAYLOAD_TOO_LARGE: 413,
    UNSUPPORTED_MEDIA_TYPE: 415,
    UNPROCESSABE_ENTITY: 422,
    LOCKED: 423,
    TOO_EARLY: 425,
    TOO_MANY_REQUESTS: 429,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,
    INTERNAL_SERVER_ERROR : 500,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    INSUFFICIENT_STORAGE: 505,
    LOOP_DETECTED: 508,
    NETWORK_AUTHENTICATION_ERROR: 511
}

module.exports = httpStatusCodes